### PR TITLE
Feature/git ssh

### PR DESCRIPTION
**Pull request by Mageti**
Hello,
Thanks for this docker, it's very useful !
May I suggest you to add the package "openssh-client" ?
The reason is : I'd like to use ssh to git clone my code inside codiad, and for this, git needs the openssh-client package installed.
I also add the instructions to make it work in the README.md

### CODE REVIEW

**Comment by CHBMB** [comment]
@sparklyballs I think this is reasonable.  Any objections?

**Comment by tobbenb** [comment]
Jenkins test this please

**Comment by CHBMB** [comment]
I'm an idiot....

**Comment by CHBMB** [comment]
Jenkins test this please

**Comment by Mageti** [comment]
Any news ?

**Comment by Mageti** [comment]
Would you like I rebase+squash this PR ?

**Comment by thelamer** [comment]
@Mageti sorry for the delay on this, I am going to piggy back this change into the 3.9 rebase here: 

https://github.com/linuxserver/docker-codiad/pull/20

When this is merged the latest image will have the client available.

**Pull request closed without merging**
